# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Neubauer Group
email: msn@illinois.edu
# The description below will appear in your document head meta (for Google
#search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
  The Neubauer Group at the University of Illinois aims to understand the
  universe at its most fundamental level, including the constituents of matter
  and their interactions. We are currently searching for physics beyond the
  standard model of particle physics through a detailed study of high-energy
  proton collisions at CERN's Large Hadron Collider using the ATLAS detector.
baseurl: /NeubauerGroup
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

# Plug-ins
plugins_dir:
  - jekyll-sitemap
  - jekyll-feed
